### ISSUE TITLE
[Feature Request] Plugins AppImages

### ISSUE THREAD

**Issue by dCo3lh0** [ivan-hc/GIMP-appimage#13]
Are you planning to package the plugins as AppImages as well? since aferrero2707 stopped? or only GIMP?

**Comment by ivan-hc** [comment]
I can package everything you ask to me, the best practice is to edit the builders by yourself, so we can get more features.

My new AppImages based on Arch Linux / JuNest can inclode everything. All we have to do later is to remove all the stuff that the app does not needs (basically, a whole Appimage of GIMP using this method is about 590 MB, if you can download an AppImage of just 97 MB is because I worked on it a whole night).

**Comment by dCo3lh0** [comment]
Here is some of the plugins for GIMP:

GMic
Lensfun
Fourier
FocurBlur
LiquidRescale
Resynthesizer
BIMP

**Comment by ivan-hc** [comment]
Can you tell me the names of the packages in Arch Linux?

Maybe in a fomat like this: `sudo pacman -S app1 app2 app3`

**Comment by dCo3lh0** [comment]
aferrero did this here:

https://github.com/aferrero2707/gimp-plugins-collection

**Comment by ivan-hc** [comment]
I didn't ask you what Ferrero did, I asked you to write me the name of the Arch Linux packages to install them

**Comment by dCo3lh0** [comment]
This here on Arch Repo
`sudo pacman -S gmic lensfun xsane gimp-nufraw`

On other hand on AUR, there is all of these here:
https://aur.archlinux.org/packages?O=0&SeB=nd&K=gimp-plugin&outdated=&SB=p&SO=d&PP=50&submit=Go

**Comment by ivan-hc** [comment]
This is already a good step.

Note that my script also uses "yay" to install packages from the AUR. You can give me a more complete list of the plugins you need (maybe not those who are outdated).

**Comment by ivan-hc** [comment]
about `xsane-gimp`, I don't think I can include it in `gimp-devel`, it may contrast with the normal `gimp`, required as dependence

**Comment by ivan-hc** [comment]
I'm starting first tests on my PC.

These are the additional dependences for:

Stable= nspr sdl2 gmic lensfun xsane xsane-gimp gimp-nufraw gimp-plugin-bimp gimp-plugin-lqr gimp-plugin-resynthesizer-git

Developer= nspr sdl2 gmic lensfun xsane gimp-nufraw

**Comment by ivan-hc** [comment]
UPDATE: GIMP Stable is about 200 MB now, some bloatwares are been added when installing the plugins.

**Comment by dCo3lh0** [comment]
`sudo yay -S gimp-plugin-gmic-git gimp-plugin-fourier-git gimp-plugin-lqr-git gimp-plugin-resynthesizer-git gimp-plugin-bimp gimp-plugin-fblur gimp-lensfun xsane-gimp-git`

from the looks of AUR, there is some that pulls from GIT and others who not.

**Comment by ivan-hc** [comment]
I urgently need a function to fetch from JuNest only what the app needs to run on JuNest, I can't spend my nights removing unnecessary files from AppDirs.

**Comment by ivan-hc** [comment]
I just opened an issue in JuNest hasking help https://github.com/fsquillace/junest/issues/336

**Comment by ivan-hc** [comment]
The work to be done on these packages is longer than expected. The advantage is that you can get an Arch Linux-based AppImage in minutes, but the problem is making it lightweight. 

For the past 24 hours I've been working on an alternative script to fetch (via "`ldd`") only the essential files for the application of interest. I tested GIMP and the final product ranged between 230 and 190 MB, depending on the improvements to be made.

The generic script I've been working on is this https://github.com/ivan-hc/ArchImage/blob/main/sample-next-junest.sh

Unfortunately, if you have a working AppImage that takes up too much space, on the other hand you have an AppImage that is too minimal and requires essential libraries, for example, to add icons to the graphical interface, and the issue is the same of those who work on .deb packages. I worked continuously on this for about twenty hours, but without success.

You're welcome to give it a try, it's always nice to have contributors to open source projects.

Anyway, I worked for months to distribute a working GIMP AppImage built from PPA, and I suppose that I can't trow away a working product in favour of an alpha project. I understand that the PPA-based one still works for everybody... so I think I have to do a step back, again.

I restored the old workflows, you can already use the latest builds from https://github.com/ivan-hc/GIMP-appimage/releases/tag/continuous

I am sorry. ArchImages still have to wait quite a while before becoming really efficient.

Greetings.

**Comment by ivan-hc** [comment]
Just added the new template for "Stable" https://github.com/ivan-hc/GIMP-appimage/blob/main/gimp-junest.sh

AppImage is 175 MB

I should work on gimp-devel now.

**Comment by ivan-hc** [comment]
Just uploaded the script for gimp-devel https://github.com/ivan-hc/GIMP-appimage/blob/main/gimp-dev-junest.sh

Appimage is about 220 MB. All this was the best I did to made them work almost perfectly.

New continuous releases will be available each Sunday at 14:00 UTC, as always, at:

https://github.com/ivan-hc/GIMP-appimage/releases/tag/continuous

Next release will be available after an half hour from this message.

Closed.

**Comment by dCo3lh0** [comment]
Just came again here to add a comment that,  the plugins you added to AppImage files, isnt working, so if you want to take it of and ignore so GIMP files is smaller, do it, because it didnt work.

**Comment by ivan-hc** [comment]
@dCo3lh0 in the last release I've added support for "gimptool", just run:

    ./.*AppImage gimptool [OPTIONS/ARGUMENTS]
to add all the plugins you want.

There are a lot of guides about the use of "gimptool", I don't use them because my use of GIMP is really basic.

With "gimptool" I let you choose the plugins by yourself.
